[package]
name = "mempool"
version = "0.1.1"
authors = ["geli <xlugeli@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
object-pool = "0.5"
crossbeam="0.7.3"
parking_lot = "0.11.0"